### ISSUE TITLE
Multiview ICA components_ attribute has bad description

### ISSUE THREAD

**Issue by gmischl1** [mvlearn/mvlearn#215]
## Expected Behavior
The [ICA docs](https://mvlearn.neurodata.io/references/decomposition.html#multiview-ica) say the MultiviewICA object has an attribute `components_` described as "np array of shape (n_groups, n_features, n_components). P is the projection matrix that projects data in reduced space".

## Actual Behavior
The `components_` attribute is a tuple of length n_groups, and it is only not None if n_components was explicitly set during creation of the MultiviewICA object. It would be good if the tuple was converted to the array of the shape described internally, and also it would be helpful if there was more description about when `components_` is not None. Also, the description mentions "P" which is not mvlearn's notation, but rather the internal code's variable.

## Template Code
```mvlearn
data = np.random.rand(25,4)
data2 = np.random.rand(25,4)
Xs = [data, data2]
ica = MultiviewICA(n_components=3)
ica.fit(Xs)
print(type(ica.components_))
print(len(ica.components_))

<class 'tuple'>
2
```

## Your Environment
* Python version: 3.7
* mvlearn version: 3.0.0

**Comment by rflperry** [comment]
@gmischl1 was resolved yes?

**Comment by gmischl1** [comment]
> @gmischl1 was resolved yes?

This one wasn't resolved. I can make a PR to resolve it. My earlier PR was just for the "Attributes" section being formatted incorrectly.
